[package]
name = "lref-provider-postgres"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "PostgreSQL provider for Rust Entity Framework"
keywords = ["orm", "efcore", "entity-framework", "postgres", "database"]
categories = ["database"]

[dependencies]
lref = { version = "0.2.0", path = "../lref" }
async-trait = "0.1"
tokio-postgres = "0.7"
deadpool-postgres = "0.14"
tokio = { version = "1", features = ["full"] }
