[package]
name = "rust-ef-mysql"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "MySQL provider for Rust Entity Framework"
keywords = ["orm", "efcore", "entity-framework", "mysql", "database"]
categories = ["database"]

[dependencies]
rust-ef = { version = "0.3.5", path = "../core" }
async-trait = "0.1"
sqlx = { version = "0.8", features = ["mysql", "runtime-tokio"] }
tokio = { version = "1", features = ["full"] }
