[workspace]
members = [
    "crates/core",
    "crates/macros",
    "crates/postgres",
    "crates/mysql",
    "crates/sqlite",
    "crates/cli",
    "examples/blog",
    "examples/soft_delete",
    "examples/audit",
]
resolver = "2"

[workspace.package]
version = "1.5.3"
edition = "2021"
license = "MIT"
repository = "https://gitcode.com/rf2026/rust-ef"
authors = ["Start"]

[workspace.dependencies]
inventory = "0.3"
