[workspace]
members = [
    "crates/rust-ef",
    "crates/rust-ef-macros",
    "crates/rust-ef-postgres",
    "crates/rust-ef-mysql",
    "crates/rust-ef-sqlite",
    "crates/rust-dicore",
    "examples/blog",
]
resolver = "2"

[workspace.package]
version = "0.3.5"
edition = "2021"
license = "MIT"
repository = "https://gitcode.com/rf2026/rust-ef"
authors = ["Start"]
