[package]
name = "rust-ef-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "CLI for Rust Entity Framework migrations"
keywords = ["orm", "efcore", "migration", "cli"]
categories = ["command-line-utilities"]

[[bin]]
name = "rust-ef"
path = "src/main.rs"

[dependencies]
rust-ef = { version = "1.1.0", path = "../core" }
rust-ef-sqlite = { version = "1.1.0", path = "../sqlite" }
rust-ef-postgres = { version = "1.1.0", path = "../postgres" }
rust-ef-mysql = { version = "1.1.0", path = "../mysql" }
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
