[package]
name = "rust-ef-postgres"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "PostgreSQL provider for Rust Entity Framework"
keywords = ["orm", "efcore", "entity-framework", "postgres", "database"]
categories = ["database"]

[dependencies]
rust-ef = { version = "0.3.5", path = "../rust-ef" }
async-trait = "0.1"
tokio-postgres = "0.7"
deadpool-postgres = "0.14"
tokio = { version = "1", features = ["full"] }
