//! Procedural macros for Rust Entity Framework (lref).
//!
//! Provides:
//! - `#[derive(EntityType)]` — generates `EntityType` trait implementation
//! - `column!()` — resolves entity fields to database column names at compile time

mod entity;
mod attributes;
mod column_macro;

use proc_macro::TokenStream;

/// Derive macro to implement `EntityType` for a struct.
///
/// Generates:
/// - `EntityTypeMeta` for the entity (table name, columns, keys, navigations)
/// - `EntityType` trait implementation
/// - `FromRow` trait implementation for materialization
/// - `COLUMN_*` associated constants for type-safe column references
///
/// # Attributes
///
/// | Attribute          | EFCore Equivalent | Description                        |
/// |--------------------|-------------------|------------------------------------|
/// | `#[table("name")]` | `[Table("name")]` | Sets the database table name       |
/// | `#[primary_key]`   | `[Key]`           | Marks as primary key               |
/// | `#[auto_increment]`| (convention)      | Auto-increment / identity          |
/// | `#[required]`      | `[Required]`      | NOT NULL constraint                |
/// | `#[max_length(N)]` | `[MaxLength(N)]`  | Maximum string length              |
/// | `#[column("name")]`| `[Column("name")]`| Different column name              |
/// | `#[foreign_key(T)]`| `[ForeignKey]`    | Marks as foreign key               |
/// | `#[navigation]`    | (navigation prop) | Marks as navigation property       |
/// | `#[not_mapped]`    | `[NotMapped]`     | Excludes from mapping              |
/// | `#[index]`         | `[Index]`         | Creates a database index           |
/// | `#[unique]`        | (unique index)    | Creates a unique database index    |
#[proc_macro_derive(EntityType, attributes(table, primary_key, auto_increment, required, max_length, column, foreign_key, navigation, not_mapped, index, unique, concurrency_check))]
pub fn derive_entity_type(input: TokenStream) -> TokenStream {
    entity::expand_entity_type(input)
}

/// Resolves an entity field to its database column name at compile time.
///
/// # Usage
///
/// ```ignore
/// use lref::column;
///
/// let col = column!(Blog::url); // "url" (or custom column name)
/// ```
///
/// Expands to `Blog::COLUMN_URL`, which is a `&'static str` constant
/// auto-generated by `#[derive(EntityType)]`.
#[proc_macro]
pub fn column(input: TokenStream) -> TokenStream {
    column_macro::expand_column(input)
}
